name = "CAMNAS"
uuid = "0b880eee-5bea-49e4-84ce-93e95af8a2a0"
authors = ["Felix Wege <fwege@eonerc.rwth-aachen.de>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUSOLVERRF = "a8cc9031-bad2-4722-94f5-40deabb4245c"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
